require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InvoicePaymentsController do

  # This should return the minimal set of attributes required to create a valid
  # InvoicePayment. As you add validations to InvoicePayment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InvoicePaymentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all invoice_payments as @invoice_payments" do
      invoice_payment = InvoicePayment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:invoice_payments).should eq([invoice_payment])
    end
  end

  describe "GET show" do
    it "assigns the requested invoice_payment as @invoice_payment" do
      invoice_payment = InvoicePayment.create! valid_attributes
      get :show, {:id => invoice_payment.to_param}, valid_session
      assigns(:invoice_payment).should eq(invoice_payment)
    end
  end

  describe "GET new" do
    it "assigns a new invoice_payment as @invoice_payment" do
      get :new, {}, valid_session
      assigns(:invoice_payment).should be_a_new(InvoicePayment)
    end
  end

  describe "GET edit" do
    it "assigns the requested invoice_payment as @invoice_payment" do
      invoice_payment = InvoicePayment.create! valid_attributes
      get :edit, {:id => invoice_payment.to_param}, valid_session
      assigns(:invoice_payment).should eq(invoice_payment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InvoicePayment" do
        expect {
          post :create, {:invoice_payment => valid_attributes}, valid_session
        }.to change(InvoicePayment, :count).by(1)
      end

      it "assigns a newly created invoice_payment as @invoice_payment" do
        post :create, {:invoice_payment => valid_attributes}, valid_session
        assigns(:invoice_payment).should be_a(InvoicePayment)
        assigns(:invoice_payment).should be_persisted
      end

      it "redirects to the created invoice_payment" do
        post :create, {:invoice_payment => valid_attributes}, valid_session
        response.should redirect_to(InvoicePayment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved invoice_payment as @invoice_payment" do
        # Trigger the behavior that occurs when invalid params are submitted
        InvoicePayment.any_instance.stub(:save).and_return(false)
        post :create, {:invoice_payment => {}}, valid_session
        assigns(:invoice_payment).should be_a_new(InvoicePayment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InvoicePayment.any_instance.stub(:save).and_return(false)
        post :create, {:invoice_payment => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested invoice_payment" do
        invoice_payment = InvoicePayment.create! valid_attributes
        # Assuming there are no other invoice_payments in the database, this
        # specifies that the InvoicePayment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InvoicePayment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => invoice_payment.to_param, :invoice_payment => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested invoice_payment as @invoice_payment" do
        invoice_payment = InvoicePayment.create! valid_attributes
        put :update, {:id => invoice_payment.to_param, :invoice_payment => valid_attributes}, valid_session
        assigns(:invoice_payment).should eq(invoice_payment)
      end

      it "redirects to the invoice_payment" do
        invoice_payment = InvoicePayment.create! valid_attributes
        put :update, {:id => invoice_payment.to_param, :invoice_payment => valid_attributes}, valid_session
        response.should redirect_to(invoice_payment)
      end
    end

    describe "with invalid params" do
      it "assigns the invoice_payment as @invoice_payment" do
        invoice_payment = InvoicePayment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InvoicePayment.any_instance.stub(:save).and_return(false)
        put :update, {:id => invoice_payment.to_param, :invoice_payment => {}}, valid_session
        assigns(:invoice_payment).should eq(invoice_payment)
      end

      it "re-renders the 'edit' template" do
        invoice_payment = InvoicePayment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InvoicePayment.any_instance.stub(:save).and_return(false)
        put :update, {:id => invoice_payment.to_param, :invoice_payment => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested invoice_payment" do
      invoice_payment = InvoicePayment.create! valid_attributes
      expect {
        delete :destroy, {:id => invoice_payment.to_param}, valid_session
      }.to change(InvoicePayment, :count).by(-1)
    end

    it "redirects to the invoice_payments list" do
      invoice_payment = InvoicePayment.create! valid_attributes
      delete :destroy, {:id => invoice_payment.to_param}, valid_session
      response.should redirect_to(invoice_payments_url)
    end
  end

end
